自動更新機能
zerotaisuke/chat-space pull request #10
Opened 2019-02-24 15:03 UTC by zerotaisuke

# what
自動更新機能の実装

# why
カリキュラムに基づいて

2019-02-25 02:02 UTC, hirozak commented on app/assets/javascripts/index.js
> +      console.log(data)
デバック消しましょう

2019-02-25 02:02 UTC, hirozak commented on app/assets/javascripts/index.js
> +         if (message.id > lastId){
コントローラでIDの比較を行ってください

2019-02-25 06:59 UTC, zerotaisuke commented on app/assets/javascripts/index.js
> +      console.log(data)
失礼しました。削除しました。

2019-02-25 07:13 UTC, zerotaisuke commented on app/assets/javascripts/index.js
> +         if (message.id > lastId){
{ @new_messages = @messages.where('id > ?', params[:id]) }
をコントローラーに追記しました。

2019-02-25 07:15 UTC, yuki-uchida requested changes

2019-02-25 07:15 UTC, yuki-uchida commented on app/assets/javascripts/index.js
> +  function autoUpdate() {
何をupdateするのかわかるような名前だといいですね

2019-02-25 07:15 UTC, yuki-uchida commented on app/assets/javascripts/index.js
> +    .done(function(data) {
dataでは、何を受け取ったのかわからないので、それがわかる名前に変えましょう

2019-02-25 07:15 UTC, yuki-uchida commented on app/assets/javascripts/index.js
> +         if (message.id > lastId){
push忘れてないですか？

2019-02-25 08:39 UTC, yuki-uchida commented
指摘に対してどのような対応をしたのかリプライする形で記述してください

2019-02-25 08:40 UTC, zerotaisuke commented on app/assets/javascripts/index.js
> +    .done(function(data) {
gropumessageに変更しました

2019-02-25 08:41 UTC, zerotaisuke commented on app/assets/javascripts/index.js
> +  function autoUpdate() {
名前を修正しました

2019-02-25 08:44 UTC, yusukeyamane commented on app/assets/javascripts/index.js
> +         if (message.id > lastId){
コントローラーに記載すればif (message.id > lastId){は不要ですね（同じ事をやっている事になるので）

2019-02-25 08:44 UTC, yusukeyamane commented on app/assets/javascripts/index.js
> +  function group_message_autoUpdate() {
関数や、変数の命名はキャメルケースで揃えましょう

2019-02-25 08:46 UTC, yusukeyamane commented
**app/assets/javascripts/message.js**と**app/assets/javascripts/index.js**の内容に重複が多いので、一つのファイルに纏めてしまいたいですね

2019-02-25 08:58 UTC, zerotaisuke commented on app/assets/javascripts/index.js
> +  function group_message_autoUpdate() {
キャメルケースへ修正しました

2019-02-25 10:32 UTC, ghost requested changes
実際の挙動をGIFでこちらに添付してください。

2019-02-25 10:32 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +         if (message.id > lastId){
コントローラーでidの比較をしているのでこちらのidの比較は不要なのではないかと思うのですがいかがでしょうか？

2019-02-25 10:32 UTC, hiroki5123 commented on app/assets/javascripts/index.js
> +  // function addNewMessagesHTML(comment){
コメントアウトするのであれば削除しましょう

2019-02-25 12:32 UTC, zerotaisuke commented
https://gyazo.com/d58af2fc7f1c01e9ce5ac35a4e1597ef

2019-02-25 12:32 UTC, zerotaisuke commented on app/assets/javascripts/index.js
> +  // function addNewMessagesHTML(comment){
削除しました

2019-02-25 12:37 UTC, zerotaisuke commented on app/assets/javascripts/message.js
> +         if (message.id > lastId){
削除しました。

2019-02-25 12:41 UTC, ghost requested changes
GIFを見る限り、ユーザーの名前がundefinedになってますが大丈夫でしょうか？

2019-02-26 09:54 UTC, zerotaisuke commented
失礼しました。修正しました。

2019-02-26 09:55 UTC, ghost approved these changes
LGTM

2019-02-26 09:55 UTC, merged