css→scss
zerotaisuke/chat-space pull request #5
Opened 2019-02-01 11:52 UTC by zerotaisuke

# what
 ビュー作成

# why
 0から作る。

2019-02-05 10:23 UTC, zerotaisuke commented
<img width="1440" alt="2019-02-05 19 14 49" src="https://user-images.githubusercontent.com/47076525/52267068-6f81bb00-297b-11e9-80a9-f722cbff6d79.png">
画面キャプチャを添付します。

2019-02-05 10:26 UTC, TOMARUMARU reviewed
ビュー画面を本番のものと見比べてもう少し近づけてください。

特にメッセージを表示する部分、メッセージ送信フォームがまだできていないかなという感じです。

後歯車のアイコンがなぜか3つありますね。。

2019-02-06 10:08 UTC, zerotaisuke commented
<img width="1440" alt="2019-02-06 19 03 19" src="https://user-images.githubusercontent.com/47076525/52334110-4c6e0e80-2a42-11e9-8ea5-5bb0bf95aada.png">
画面キャプチャを添付します。前回、 #AAAAAAとしていた一部の箇所は色指定がなかったので、仮で白としました。

2019-02-06 10:13 UTC, yuki-uchida commented
下部の画像アイコンとsendボタンの間は25pxになっていますか？
また、画面右のpaddingは40pxになっていますか？

2019-02-06 10:14 UTC, yuki-uchida requested changes
コードを見ても、やはりなっていないように見えます。
もしなっているのであれば、どちらのコードがそれを意味しているかお知らせください

2019-02-07 07:57 UTC, zerotaisuke commented
下部の画像アイコンとsendボタンの間を25pxに修正しました。画像右のpadding40pxについては、上部のボタンはfloatで右に寄せ、右から40pxとしました。下部のボタンはsendボタンからの距離を優先させたため、特に指定していません。
<img width="1440" alt="2019-02-07 16 46 24" src="https://user-images.githubusercontent.com/47076525/52397558-50109c80-2af9-11e9-88a9-0ea6493d1b2d.png">

2019-02-07 07:59 UTC, yuki-uchida approved these changes
LGTMです！

2019-02-07 08:04 UTC, merged