first commit
zerotaisuke/chat-space pull request #8
Opened 2019-02-18 07:35 UTC by zerotaisuke

# what
非同期通信の実装

# why
have to

2019-02-19 10:16 UTC, ghost requested changes

2019-02-19 10:16 UTC, hiroki5123 commented on app/controllers/messages_controller.rb
> +      # redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'
不要であれば削除しましょう

2019-02-19 10:16 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +  // console.log(hoge);
こちらも

2019-02-19 10:16 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +         `<div class="message" data-message-id=${message.id}>
記述が同じところがあって冗長になっているので、リファクタリングしましょう

2019-02-21 11:29 UTC, zerotaisuke commented on app/controllers/messages_controller.rb
> +      # redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'
削除しました

2019-02-21 11:29 UTC, zerotaisuke commented on app/assets/javascripts/message.js
> +  // console.log(hoge);
削除しました

2019-02-21 11:29 UTC, zerotaisuke commented on app/assets/javascripts/message.js
> +         `<div class="message" data-message-id=${message.id}>
リファクタリングしました

2019-02-21 11:34 UTC, yuki-uchida requested changes

2019-02-21 11:34 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +  .done(function(data){
dataでは、何を受け取ったのかわからないので、それがわかる名前に変えましょう

2019-02-21 11:34 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +$('#js_form').on('submit', function(e){
js_formではわかりづらいので名前を変えましょう

2019-02-21 11:34 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +  function buildHTML(message){
buildHTMLでは、何をどうするのかがわかりづらいので、buildSendMessageHTMLとかいかがでしょうか

2019-02-21 11:34 UTC, yuki-uchida commented on app/controllers/messages_controller.rb
> +    # respond_to do |format|
コメントアウトは消してからプルリクを出してください。
また、これ消してあってきちんと動いていますか？

2019-02-21 12:37 UTC, zerotaisuke commented on app/assets/javascripts/message.js
> +  .done(function(data){
latestmessageに変更しました

2019-02-21 12:38 UTC, zerotaisuke commented on app/assets/javascripts/message.js
> +$('#js_form').on('submit', function(e){
SendMessage　に変更しました

2019-02-21 12:38 UTC, zerotaisuke commented on app/assets/javascripts/message.js
> +  function buildHTML(message){
buildSendMessageHTML　に変更しました

2019-02-21 12:43 UTC, zerotaisuke commented on app/controllers/messages_controller.rb
> +    # respond_to do |format|
消しても動いています。

2019-02-21 12:44 UTC, zerotaisuke commented on app/controllers/messages_controller.rb
> +    # respond_to do |format|
コメントアウトは削除しました

2019-02-21 12:46 UTC, yuki-uchida approved these changes
LGTMです。お疲れ様でした

2019-02-21 12:57 UTC, merged